import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import { inter, interDisplay } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background", inter.variable, interDisplay.variable)}
      >
        {children}
      </body>
    </html>
  );
}
